---
name: Test Action

on: [push, workflow_dispatch]

jobs:
  test_action:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
        with:
          path: ./action
      - uses: actions/checkout@v4
        with:
          repository: zckv/semantic-versioning-example
          path: ./pyproject
      - uses: ./action
        with:
          root_options: -v
          directory: ./pyproject
          commit: false
          psr_version: 8.3.0
